projects:
  - badger-css
  - badger-react-ui
  - badger-icon
  - badger-form
  - badger-color
  - badger-js
  - badger-database
  - badger-filesystem
  - badger-utils
  - badger-timestamp
  - react-context
  - react-night-and-day
  - react-one-louder
  - spinal-tapsum
